In [18]:
import pandas as pd
import numpy as np
import os
# import gc
from typing import Iterator, Union, List, Optional
from pathlib import Path
import shutil
from sqlalchemy import create_engine
from sqlalchemy import URL

In [8]:
df_database = pd.read_parquet("./planning_data/database/database_cleaned.parquet", engine="pyarrow")
df_database

,Time_Bucket,Hub In/Out,Location - Monthly Ped Report,Zone Number,Count
0,2020-02-24 00:00:00,IN,1 Train North,23,1.0
1,2020-02-24 00:00:00,IN,1 Train North,30,9.0
2,2020-02-24 00:00:00,IN,1 Train South,28,0.0
3,2020-02-24 00:00:00,IN,1 Train South,29,3.0
4,2020-02-24 00:00:00,IN,2 WTC Transit Lobby,11,21.0
...,...,...,...,...,...
3691003,2024-08-31 23:30:00,OUT,PATH Turnstiles,21,0.0
3691004,2024-08-31 23:30:00,OUT,R/W Train North,25,38.0
3691005,2024-08-31 23:30:00,OUT,R/W Train South,22,7.0
3691006,2024-08-31 23:30:00,OUT,T3 Transit Lobby,27,10.0
3691007,2024-08-31 23:30:00,OUT,West Oculus Projection,5,25.0

In [17]:
df_database.columns = [c.lower() for c in df_database.columns] #postgres doesn't like capitals or spaces
df_database.columns = df_database.columns.str.replace('[^a-zA-Z0-9]', '').str.lower()
df_database.columns = df_database.columns.str.replace("/", '_')
df_database.columns = df_database.columns.str.replace(r' ', '_')
df_database.columns = df_database.columns.str.replace('-', '')
df_database.columns = df_database.columns.str.strip('_')
df_database

,time_bucket,hub_in_out,location__monthly_ped_report,zone_number,count
0,2020-02-24 00:00:00,IN,1 Train North,23,1.0
1,2020-02-24 00:00:00,IN,1 Train North,30,9.0
2,2020-02-24 00:00:00,IN,1 Train South,28,0.0
3,2020-02-24 00:00:00,IN,1 Train South,29,3.0
4,2020-02-24 00:00:00,IN,2 WTC Transit Lobby,11,21.0
...,...,...,...,...,...
3691003,2024-08-31 23:30:00,OUT,PATH Turnstiles,21,0.0
3691004,2024-08-31 23:30:00,OUT,R/W Train North,25,38.0
3691005,2024-08-31 23:30:00,OUT,R/W Train South,22,7.0
3691006,2024-08-31 23:30:00,OUT,T3 Transit Lobby,27,10.0
3691007,2024-08-31 23:30:00,OUT,West Oculus Projection,5,25.0

In [24]:
url_object = URL.create(
    "postgresql",
    username="postgres",
    password="DeathLife!@#",  # plain (unescaped) text
    host="localhost",
    database="Xovis_Counts",
)
engine = create_engine(url_object)

In [25]:
df_database.to_sql("database_cleaned", engine)

8